name: nodeseek鸡腿签到

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 16 * * *'  # UTC 16:00 触发 = 北京时间 00:00
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest

    steps:
      - name: 随机延迟 0-1800 秒（0~30分钟）
        run: |
          DELAY=$(( RANDOM % 1800 ))
          echo "随机延迟 $DELAY 秒（约 $((DELAY/60)) 分钟）"
          sleep $DELAY

      - name: 检出代码仓库
        uses: actions/checkout@v3
      
      - name: 配置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: 安装依赖包
        run: |
          pip install curl_cffi requests --upgrade

      - name: 运行签到脚本
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          USER1: ${{ secrets.USER1 }}
          PASS1: ${{ secrets.PASS1 }}
          USER2: ${{ secrets.USER2 }}
          PASS2: ${{ secrets.PASS2 }}
          USER3: ${{ secrets.USER3 }}
          PASS3: ${{ secrets.PASS3 }}
          USER4: ${{ secrets.USER4 }}
          PASS4: ${{ secrets.PASS4 }}
          USER5: ${{ secrets.USER5 }}
          PASS5: ${{ secrets.PASS5 }}

          NS_COOKIE: ${{ vars.NS_COOKIE || secrets.NS_COOKIE }}

          SOLVER_TYPE: ${{ secrets.SOLVER_TYPE }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          CLIENTT_KEY: ${{ secrets.CLIENTT_KEY }}

          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}

          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
        run: python nodeseek_sign.py
